/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/boats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatSummaryDto"][];
                        "application/json": components["schemas"]["BoatSummaryDto"][];
                        "text/json": components["schemas"]["BoatSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BoatUpsertRequest"];
                    "text/json": components["schemas"]["BoatUpsertRequest"];
                    "application/*+json": components["schemas"]["BoatUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDetailDto"];
                        "application/json": components["schemas"]["BoatDetailDto"];
                        "text/json": components["schemas"]["BoatDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDetailDto"];
                        "application/json": components["schemas"]["BoatDetailDto"];
                        "text/json": components["schemas"]["BoatDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BoatUpsertRequest"];
                    "text/json": components["schemas"]["BoatUpsertRequest"];
                    "application/*+json": components["schemas"]["BoatUpsertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDetailDto"];
                        "application/json": components["schemas"]["BoatDetailDto"];
                        "text/json": components["schemas"]["BoatDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boats/{id}/unavailabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnavailabilityDto"][];
                        "application/json": components["schemas"]["UnavailabilityDto"][];
                        "text/json": components["schemas"]["UnavailabilityDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnavailabilityRequest"];
                    "text/json": components["schemas"]["UnavailabilityRequest"];
                    "application/*+json": components["schemas"]["UnavailabilityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnavailabilityDto"];
                        "application/json": components["schemas"]["UnavailabilityDto"];
                        "text/json": components["schemas"]["UnavailabilityDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boats/{id}/unavailabilities/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnavailabilityRequest"];
                    "text/json": components["schemas"]["UnavailabilityRequest"];
                    "application/*+json": components["schemas"]["UnavailabilityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnavailabilityDto"];
                        "application/json": components["schemas"]["UnavailabilityDto"];
                        "text/json": components["schemas"]["UnavailabilityDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    includeInactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimelineDto"];
                        "application/json": components["schemas"]["TimelineDto"];
                        "text/json": components["schemas"]["TimelineDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminBookingRequest"];
                    "text/json": components["schemas"]["AdminBookingRequest"];
                    "application/*+json": components["schemas"]["AdminBookingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingSearchResultDto"][];
                        "application/json": components["schemas"]["BookingSearchResultDto"][];
                        "text/json": components["schemas"]["BookingSearchResultDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    boatId?: string;
                    periodType?: components["schemas"]["PeriodType"];
                    startDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminQuoteDto"];
                        "application/json": components["schemas"]["AdminQuoteDto"];
                        "text/json": components["schemas"]["AdminQuoteDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminBookingUpdateRequest"];
                    "text/json": components["schemas"]["AdminBookingUpdateRequest"];
                    "application/*+json": components["schemas"]["AdminBookingUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/recalculate-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionRequest"];
                    "text/json": components["schemas"]["VersionRequest"];
                    "application/*+json": components["schemas"]["VersionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/addons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddAddonLineRequest"];
                    "text/json": components["schemas"]["AddAddonLineRequest"];
                    "application/*+json": components["schemas"]["AddAddonLineRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/addons/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAddonLineRequest"];
                    "text/json": components["schemas"]["UpdateAddonLineRequest"];
                    "application/*+json": components["schemas"]["UpdateAddonLineRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                    lineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualPaymentRequest"];
                    "text/json": components["schemas"]["ManualPaymentRequest"];
                    "application/*+json": components["schemas"]["ManualPaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingDetailDto"];
                        "application/json": components["schemas"]["BookingDetailDto"];
                        "text/json": components["schemas"]["BookingDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/send-payment-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SendPaymentLinkResult"];
                        "application/json": components["schemas"]["SendPaymentLinkResult"];
                        "text/json": components["schemas"]["SendPaymentLinkResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerDto"][];
                        "application/json": components["schemas"]["CustomerDto"][];
                        "text/json": components["schemas"]["CustomerDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/by-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    email?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerDto"];
                        "application/json": components["schemas"]["CustomerDto"];
                        "text/json": components["schemas"]["CustomerDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusinessSettingsDto"];
                        "application/json": components["schemas"]["BusinessSettingsDto"];
                        "text/json": components["schemas"]["BusinessSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BusinessSettingsDto"];
                    "text/json": components["schemas"]["BusinessSettingsDto"];
                    "application/*+json": components["schemas"]["BusinessSettingsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusinessSettingsDto"];
                        "application/json": components["schemas"]["BusinessSettingsDto"];
                        "text/json": components["schemas"]["BusinessSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeasonDto"][];
                        "application/json": components["schemas"]["SeasonDto"][];
                        "text/json": components["schemas"]["SeasonDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeasonRequest"];
                    "text/json": components["schemas"]["SeasonRequest"];
                    "application/*+json": components["schemas"]["SeasonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeasonDto"];
                        "application/json": components["schemas"]["SeasonDto"];
                        "text/json": components["schemas"]["SeasonDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/seasons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeasonRequest"];
                    "text/json": components["schemas"]["SeasonRequest"];
                    "application/*+json": components["schemas"]["SeasonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SeasonDto"];
                        "application/json": components["schemas"]["SeasonDto"];
                        "text/json": components["schemas"]["SeasonDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/blocked-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BlockedPeriodDto"][];
                        "application/json": components["schemas"]["BlockedPeriodDto"][];
                        "text/json": components["schemas"]["BlockedPeriodDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlockedPeriodRequest"];
                    "text/json": components["schemas"]["BlockedPeriodRequest"];
                    "application/*+json": components["schemas"]["BlockedPeriodRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BlockedPeriodDto"];
                        "application/json": components["schemas"]["BlockedPeriodDto"];
                        "text/json": components["schemas"]["BlockedPeriodDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/blocked-periods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BlockedPeriodRequest"];
                    "text/json": components["schemas"]["BlockedPeriodRequest"];
                    "application/*+json": components["schemas"]["BlockedPeriodRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BlockedPeriodDto"];
                        "application/json": components["schemas"]["BlockedPeriodDto"];
                        "text/json": components["schemas"]["BlockedPeriodDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/addons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AddonDto"][];
                        "application/json": components["schemas"]["AddonDto"][];
                        "text/json": components["schemas"]["AddonDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddonRequest"];
                    "text/json": components["schemas"]["AddonRequest"];
                    "application/*+json": components["schemas"]["AddonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AddonDto"];
                        "application/json": components["schemas"]["AddonDto"];
                        "text/json": components["schemas"]["AddonDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/addons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddonRequest"];
                    "text/json": components["schemas"]["AddonRequest"];
                    "application/*+json": components["schemas"]["AddonRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AddonDto"];
                        "application/json": components["schemas"]["AddonDto"];
                        "text/json": components["schemas"]["AddonDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmailTemplatesDto"];
                        "application/json": components["schemas"]["EmailTemplatesDto"];
                        "text/json": components["schemas"]["EmailTemplatesDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email-templates/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: components["schemas"]["EmailTemplateKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailTemplateRequest"];
                    "text/json": components["schemas"]["EmailTemplateRequest"];
                    "application/*+json": components["schemas"]["EmailTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmailTemplateDto"];
                        "application/json": components["schemas"]["EmailTemplateDto"];
                        "text/json": components["schemas"]["EmailTemplateDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/email-templates/{key}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: components["schemas"]["EmailTemplateKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddAddonLineRequest: {
            /** Format: int32 */
            version: number;
            addonId: string;
            /** Format: int32 */
            quantity: number;
        };
        AddonDto: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            description: null | string;
            priceOnRequest: boolean;
            prices: null | components["schemas"]["AddonPricesDto"];
            quantityApplies: boolean;
            isActive: boolean;
        };
        AddonLineDto: {
            id: string;
            addonId: string;
            name: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            unitPrice: null | number;
            status: components["schemas"]["AddonLineStatus"];
            /** Format: double */
            lineTotal: null | number;
        };
        /** @enum {unknown} */
        AddonLineStatus: "Requested" | "Confirmed" | "Declined";
        AddonPricesDto: {
            /** Format: double */
            midweek: number;
            /** Format: double */
            weekend: number;
            /** Format: double */
            week: number;
        };
        AddonRequest: {
            /** Format: int32 */
            version: number;
            name: string;
            description: null | string;
            priceOnRequest: boolean;
            prices: null | components["schemas"]["AddonPricesDto"];
            quantityApplies: boolean;
            isActive: boolean;
        };
        AdminBookingRequest: {
            boatId: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            /** Format: int32 */
            numberOfGuests: number;
            email: null | string;
            fullName: null | string;
            phone: null | string;
            isStandby: boolean;
            comments: null | string;
            /** Format: double */
            hirePrice: null | number;
        };
        AdminBookingUpdateRequest: {
            /** Format: int32 */
            version: number;
            boatId: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            /** Format: int32 */
            numberOfGuests: number;
            email: null | string;
            fullName: null | string;
            phone: null | string;
            isStandby: boolean;
            comments: null | string;
            /** Format: double */
            hirePrice: number;
            status: components["schemas"]["BookingStatus"];
        };
        AdminQuoteDto: {
            /** Format: double */
            hirePrice: null | number;
            seasonName: null | string;
            /** Format: date */
            endDate: null | string;
            paymentSchedule: null | components["schemas"]["PaymentSchedule"];
            message: null | string;
        };
        BlockedPeriodDto: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
            usesExtendedPaymentSchedule: boolean;
        };
        BlockedPeriodRequest: {
            /** Format: int32 */
            version: number;
            name: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
            usesExtendedPaymentSchedule: boolean;
        };
        BoatDetailDto: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            slug: string;
            type: components["schemas"]["BoatType"];
            /** Format: int32 */
            maxNoOfGuests: number;
            /** Format: int32 */
            noOfBeds: null | number;
            beddingDescription: null | string;
            /** Format: double */
            securityBond: number;
            rates: components["schemas"]["BoatRateDto"][];
            allowedAddonIds: string[];
            isActive: boolean;
            missingActivationData: string[];
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string;
        };
        BoatRateDto: {
            seasonId: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: double */
            price: number;
        };
        BoatSummaryDto: {
            id: string;
            name: string;
            slug: string;
            type: components["schemas"]["BoatType"];
            /** Format: int32 */
            maxNoOfGuests: number;
            /** Format: int32 */
            noOfBeds: null | number;
            isActive: boolean;
        };
        /** @enum {unknown} */
        BoatType: "House" | "BBQ";
        BoatUpsertRequest: {
            /** Format: int32 */
            version: number;
            name: string;
            slug: string;
            /** Format: int32 */
            maxNoOfGuests: number;
            /** Format: int32 */
            noOfBeds: null | number;
            beddingDescription: null | string;
            /** Format: double */
            securityBond: number;
            rates: null | components["schemas"]["BoatRateDto"][];
            allowedAddonIds: null | string[];
            isActive: boolean;
        };
        /** @enum {unknown} */
        BookingCreatedBy: "Customer" | "SystemUser";
        BookingDetailDto: {
            id: string;
            /** Format: int32 */
            version: number;
            reference: string;
            createdBy: components["schemas"]["BookingCreatedBy"];
            isStandby: boolean;
            status: components["schemas"]["BookingStatus"];
            boatId: string;
            boatName: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: int32 */
            numberOfGuests: number;
            comments: null | string;
            /** Format: double */
            hirePrice: number;
            /** Format: double */
            depositAmount: number;
            paymentSchedule: components["schemas"]["PaymentSchedule"];
            customer: components["schemas"]["CustomerDto"];
            addonLines: components["schemas"]["AddonLineDto"][];
            payments: components["schemas"]["PaymentDto"][];
            /** Format: double */
            totalPrice: number;
            /** Format: double */
            amountPaid: number;
            /** Format: double */
            amountOwing: number;
            /** Format: double */
            amountDueNow: number;
            paymentStatus: components["schemas"]["PaymentStatus"];
            milestones: components["schemas"]["MilestoneDto"][];
            /** Format: date-time */
            holdExpiresAt: null | string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string;
            /** Format: date-time */
            termsAcceptedAt: null | string;
            /** Format: date-time */
            roomingWarningAcceptedAt: null | string;
            roomingWarningText: null | string;
            groupRestrictionDeclaredNotApplicable: null | boolean;
            sentNotifications: components["schemas"]["SentNotification"][];
        };
        BookingSearchResultDto: {
            id: string;
            reference: string;
            boatName: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            status: components["schemas"]["BookingStatus"];
            isStandby: boolean;
            customerName: string;
            customerEmail: string;
        };
        /** @enum {unknown} */
        BookingStatus: "PendingPayment" | "Active" | "Superseded" | "Cancelled" | "Expired";
        BusinessSettingsDto: {
            /** Format: int32 */
            version: number;
            /** Format: double */
            depositAmount: number;
            /** Format: int32 */
            minimumLeadTimeDays: number;
            /** Format: date */
            bookingsOpenUntil: string;
            staffAlertEmail: string;
            contactPhone: string;
            contactEmail: string;
            hireTermsUrl: string;
        };
        CustomerDto: {
            id: string;
            fullName: string;
            email: string;
            mobileNumber: null | string;
            /** Format: date-time */
            createdDate: string;
        };
        EmailTemplateDto: {
            key: components["schemas"]["EmailTemplateKey"];
            /** Format: int32 */
            version: number;
            subject: string;
            htmlBody: string;
        };
        /** @enum {unknown} */
        EmailTemplateKey: "BookingConfirmed" | "StaffNewOnlineBooking" | "PaymentDue" | "PaymentReceived" | "PreHireInstructions" | "StaffBalanceOverdue" | "StaffStandbySuperseded";
        EmailTemplateRequest: {
            /** Format: int32 */
            version: number;
            subject: string;
            htmlBody: string;
        };
        EmailTemplatesDto: {
            templates: components["schemas"]["EmailTemplateDto"][];
            placeholders: string[];
        };
        ManualPaymentRequest: {
            /** Format: int32 */
            version: number;
            /** Format: double */
            amount: number;
            /** Format: date */
            date: string;
            note: null | string;
        };
        MilestoneDto: {
            kind: components["schemas"]["MilestoneKind"];
            label: string;
            /** Format: double */
            amount: number;
            /** Format: double */
            requiredCumulative: number;
            /** Format: date */
            dueDate: null | string;
        };
        /** @enum {unknown} */
        MilestoneKind: "Deposit" | "Balance" | "FirstInstalment" | "Final";
        PaymentDto: {
            id: string;
            /** Format: double */
            amount: number;
            method: components["schemas"]["PaymentMethod"];
            stripePaymentIntentId: null | string;
            /** Format: date-time */
            paidAt: string;
            note: null | string;
            recordedBy: components["schemas"]["PaymentRecordedBy"];
        };
        /** @enum {unknown} */
        PaymentMethod: "Stripe" | "Manual";
        /** @enum {unknown} */
        PaymentRecordedBy: "Customer" | "SystemUser";
        /** @enum {unknown} */
        PaymentSchedule: "Standard" | "Extended";
        /** @enum {unknown} */
        PaymentStatus: "Outstanding" | "DepositPaid" | "PartPaid" | "FullyPaid";
        /** @enum {unknown} */
        PeriodType: "Midweek" | "Weekend" | "Week" | "LongWeekend" | "Custom";
        SeasonDto: {
            id: string;
            /** Format: int32 */
            version: number;
            name: string;
            isDefault: boolean;
            ranges: components["schemas"]["SeasonRangeDto"][];
        };
        SeasonRangeDto: {
            startDayMonth: string;
            endDayMonth: string;
        };
        SeasonRequest: {
            /** Format: int32 */
            version: number;
            name: string;
            ranges: null | components["schemas"]["SeasonRangeDto"][];
        };
        SendPaymentLinkResult: {
            sentTo: string;
            /** Format: double */
            amountDue: number;
        };
        SentNotification: {
            key: string;
            /** Format: date-time */
            sentAt: string;
        };
        TimelineBlockedPeriodDto: {
            id: string;
            name: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
        };
        TimelineBoatDto: {
            id: string;
            name: string;
            isActive: boolean;
        };
        TimelineBookingDto: {
            id: string;
            reference: string;
            boatId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            periodType: components["schemas"]["PeriodType"];
            status: components["schemas"]["BookingStatus"];
            isStandby: boolean;
            paymentStatus: components["schemas"]["PaymentStatus"];
            customerName: string;
        };
        TimelineDto: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            boats: components["schemas"]["TimelineBoatDto"][];
            bookings: components["schemas"]["TimelineBookingDto"][];
            unavailabilities: components["schemas"]["TimelineUnavailabilityDto"][];
            blockedPeriods: components["schemas"]["TimelineBlockedPeriodDto"][];
        };
        TimelineUnavailabilityDto: {
            id: string;
            boatId: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
            comments: null | string;
        };
        UnavailabilityDto: {
            id: string;
            /** Format: int32 */
            version: number;
            boatId: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
            comments: null | string;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string;
        };
        UnavailabilityRequest: {
            /** Format: int32 */
            version: number;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
            comments: null | string;
        };
        UpdateAddonLineRequest: {
            /** Format: int32 */
            version: number;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            unitPrice: null | number;
            status: components["schemas"]["AddonLineStatus"];
        };
        VersionRequest: {
            /** Format: int32 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
