/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/boats/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicBoatDto"];
                        "application/json": components["schemas"]["PublicBoatDto"];
                        "text/json": components["schemas"]["PublicBoatDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boats/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AvailabilityDto"];
                        "application/json": components["schemas"]["AvailabilityDto"];
                        "text/json": components["schemas"]["AvailabilityDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boats/{slug}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuoteRequest"];
                    "text/json": components["schemas"]["QuoteRequest"];
                    "application/*+json": components["schemas"]["QuoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["QuoteDto"];
                        "application/json": components["schemas"]["QuoteDto"];
                        "text/json": components["schemas"]["QuoteDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOnlineBookingRequest"];
                    "text/json": components["schemas"]["CreateOnlineBookingRequest"];
                    "application/*+json": components["schemas"]["CreateOnlineBookingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateOnlineBookingResult"];
                        "application/json": components["schemas"]["CreateOnlineBookingResult"];
                        "text/json": components["schemas"]["CreateOnlineBookingResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{reference}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    session_id?: string;
                };
                header?: never;
                path: {
                    reference: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BookingStatusDto"];
                        "application/json": components["schemas"]["BookingStatusDto"];
                        "text/json": components["schemas"]["BookingStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PayPageDto"];
                        "application/json": components["schemas"]["PayPageDto"];
                        "text/json": components["schemas"]["PayPageDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{token}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PayCheckoutResult"];
                        "application/json": components["schemas"]["PayCheckoutResult"];
                        "text/json": components["schemas"]["PayCheckoutResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddonPricesDto: {
            /** Format: double */
            midweek: number;
            /** Format: double */
            weekend: number;
            /** Format: double */
            week: number;
        };
        AvailabilityDto: {
            unavailable: components["schemas"]["DateRangeDto"][];
            enquireOnly: components["schemas"]["EnquireOnlyDto"][];
        };
        BookingAddonRequest: {
            addonId: string;
            /** Format: int32 */
            quantity: number;
        };
        /** @enum {unknown} */
        BookingStatus: "PendingPayment" | "Active" | "Superseded" | "Cancelled" | "Expired";
        BookingStatusDto: {
            reference: string;
            status: components["schemas"]["BookingStatus"];
            boatName: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            email: string;
            /** Format: double */
            amountPaid: number;
        };
        CreateOnlineBookingRequest: {
            slug: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: int32 */
            numberOfGuests: number;
            fullName: null | string;
            email: null | string;
            mobile: null | string;
            addons: null | components["schemas"]["BookingAddonRequest"][];
            roomingWarningAccepted: boolean;
            roomingWarningText: null | string;
            groupRestrictionApplies: null | boolean;
            termsAccepted: boolean;
            turnstileToken: null | string;
        };
        CreateOnlineBookingResult: {
            reference: string;
            clientSecret: string;
            sessionId: string;
            /** Format: double */
            amount: number;
        };
        DateRangeDto: {
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
        };
        EnquireOnlyDto: {
            name: string;
            /** Format: date */
            firstNight: string;
            /** Format: date */
            lastNight: string;
        };
        MilestoneDto: {
            kind: components["schemas"]["MilestoneKind"];
            label: string;
            /** Format: double */
            amount: number;
            /** Format: double */
            requiredCumulative: number;
            /** Format: date */
            dueDate: null | string;
        };
        /** @enum {unknown} */
        MilestoneKind: "Deposit" | "Balance" | "FirstInstalment" | "Final";
        PayCheckoutResult: {
            clientSecret: string;
            sessionId: string;
            /** Format: double */
            amount: number;
        };
        /** @enum {unknown} */
        PaymentSchedule: "Standard" | "Extended";
        PayPageDto: {
            reference: string;
            boatName: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: double */
            totalPrice: number;
            /** Format: double */
            amountPaid: number;
            /** Format: double */
            amountOwing: number;
            /** Format: double */
            amountDueNow: number;
            canPay: boolean;
        };
        /** @enum {unknown} */
        PeriodType: "Midweek" | "Weekend" | "Week" | "LongWeekend" | "Custom";
        PublicAddonDto: {
            id: string;
            name: string;
            description: null | string;
            priceOnRequest: boolean;
            quantityApplies: boolean;
            prices: null | components["schemas"]["AddonPricesDto"];
        };
        PublicBoatDto: {
            slug: string;
            name: string;
            /** Format: int32 */
            maxNoOfGuests: number;
            /** Format: int32 */
            noOfBeds: null | number;
            beddingDescription: null | string;
            /** Format: double */
            securityBond: number;
            isActive: boolean;
            addons: components["schemas"]["PublicAddonDto"][];
            settings: components["schemas"]["PublicBookingSettingsDto"];
        };
        PublicBookingSettingsDto: {
            /** Format: int32 */
            minimumLeadTimeDays: number;
            /** Format: date */
            bookingsOpenUntil: string;
            contactPhone: string;
            contactEmail: string;
            hireTermsUrl: string;
            /** Format: date */
            today: string;
            checkInTime: string;
            checkOutTime: string;
        };
        QuoteAddonDto: {
            addonId: string;
            name: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            unitPrice: null | number;
            /** Format: double */
            estimatedTotal: null | number;
        };
        QuoteDto: {
            boatName: string;
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            checkInTime: string;
            checkOutTime: string;
            /** Format: int32 */
            numberOfGuests: number;
            seasonName: string;
            /** Format: double */
            hirePrice: number;
            addons: components["schemas"]["QuoteAddonDto"][];
            /** Format: double */
            depositAmount: number;
            /** Format: double */
            amountDueAtCheckout: number;
            fullPaymentAtCheckout: boolean;
            paymentSchedule: components["schemas"]["PaymentSchedule"];
            milestones: components["schemas"]["MilestoneDto"][];
            roomingWarningText: null | string;
            /** Format: double */
            securityBond: number;
        };
        QuoteRequest: {
            periodType: components["schemas"]["PeriodType"];
            /** Format: date */
            startDate: string;
            /** Format: int32 */
            numberOfGuests: number;
            addons: null | components["schemas"]["BookingAddonRequest"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
